"""Issue escalation — after N consecutive failures, offer to create a GitHub issue.

CLI mode: prompts the user interactively.
Non-interactive / MCP mode: returns the issue body for the caller to handle.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from orchestrator.task_queue import Task


def build_issue_body(
    task: Task,
    failure_count: int,
    last_errors: dict[str, str],
) -> str:
    """Build a Markdown issue body from failure context."""
    lines = [
        f"## Repeated failure: {task.id}",
        "",
        f"**Task:** {task.description}",
        f"**Consecutive failures:** {failure_count}",
        "",
        "### Last failure details",
        "",
    ]
    for gate, error in last_errors.items():
        lines += [f"**{gate}:**", "```", error.strip()[:500], "```", ""]

    lines += [
        "---",
        "*Auto-generated by jibuff issue escalation*",
    ]
    return "\n".join(lines)


def create_github_issue(
    task: Task,
    failure_count: int,
    last_errors: dict[str, str],
    workspace: Path,
    labels: list[str] | None = None,
) -> str | None:
    """Create a GitHub issue via `gh` CLI.

    Returns the issue URL on success, None on failure.
    """
    title = f"[jibuff] {task.id} failed {failure_count}x: {task.description[:60]}"
    body = build_issue_body(task, failure_count, last_errors)

    cmd = ["gh", "issue", "create", "--title", title, "--body", body]
    if labels:
        cmd += ["--label", ",".join(labels)]

    try:
        result = subprocess.run(
            cmd,
            cwd=workspace,
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            return result.stdout.strip()  # issue URL
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return None


def prompt_escalation(
    task: Task,
    failure_count: int,
    last_errors: dict[str, str],
    workspace: Path,
) -> str | None:
    """Interactive prompt: ask the user whether to create a GitHub issue.

    Returns the issue URL if created, None otherwise.
    """
    print(f"\n[jibuff] Task {task.id} has failed {failure_count} times consecutively.")
    print(f"  Task: {task.description}")
    for gate, error in last_errors.items():
        print(f"  [{gate}] {error.strip()[:100]}")

    try:
        answer = input("\nCreate a GitHub issue for this failure? [y/N] ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        return None

    if answer in ("y", "yes"):
        url = create_github_issue(
            task, failure_count, last_errors, workspace, labels=["jibuff", "bug"]
        )
        if url:
            print(f"[jibuff] Issue created: {url}")
        else:
            print("[jibuff] Failed to create issue (is `gh` CLI installed and authenticated?)")
        return url

    return None
